// Goal templates organized by life stage

export const LIFE_STAGES = [
    {
        id: 'student',
        title: 'Student',
        emoji: '🎓',
        ageRange: '15-22',
        description: 'Focus on academics, skill development, and building foundations',
    },
    {
        id: 'early-career',
        title: 'Early Career',
        emoji: '🚀',
        ageRange: '22-30',
        description: 'Career growth, professional certifications, and financial start',
    },
    {
        id: 'mid-career',
        title: 'Mid Career',
        emoji: '⚡',
        ageRange: '30-45',
        description: 'Leadership, investments, family planning, and health focus',
    },
    {
        id: 'pre-retirement',
        title: 'Pre-Retirement',
        emoji: '🏔️',
        ageRange: '45-60',
        description: 'Wealth optimization, health, lifelong learning, and legacy',
    },
    {
        id: 'active-senior',
        title: 'Active Senior',
        emoji: '🌅',
        ageRange: '60+',
        description: 'Health maintenance, hobbies, travel, and estate planning',
    },
];

export const GOAL_CATEGORIES = {
    study: {
        id: 'study',
        label: 'Study & Learning',
        emoji: '📚',
        color: '#6366f1',
        badgeClass: 'badge-study',
        eventClass: 'study',
    },
    health: {
        id: 'health',
        label: 'Health & Fitness',
        emoji: '💪',
        color: '#22c55e',
        badgeClass: 'badge-health',
        eventClass: 'health',
    },
    finance: {
        id: 'finance',
        label: 'Financial',
        emoji: '💰',
        color: '#f59e0b',
        badgeClass: 'badge-finance',
        eventClass: 'finance',
    },
    career: {
        id: 'career',
        label: 'Career & Skills',
        emoji: '🎯',
        color: '#ec4899',
        badgeClass: 'badge-career',
        eventClass: 'career',
    },
};

export const GOAL_TEMPLATES = {
    student: [
        {
            id: 'exam-prep',
            title: 'Exam Preparation',
            category: 'study',
            emoji: '📝',
            description: 'Systematic study plan with spaced repetition for upcoming exams',
            estimatedHours: 120,
            defaultWeeklyHours: 15,
            difficulty: 'Medium',
            milestones: [
                { title: 'Review syllabus & gather materials', percent: 5 },
                { title: 'Complete foundational topics', percent: 30 },
                { title: 'Practice problems & past papers', percent: 60 },
                { title: 'Mock exams & weak area review', percent: 85 },
                { title: 'Final revision & exam day', percent: 100 },
            ],
        },
        {
            id: 'learn-programming',
            title: 'Learn Programming',
            category: 'study',
            emoji: '💻',
            description: 'Master a programming language from basics to project-ready',
            estimatedHours: 200,
            defaultWeeklyHours: 10,
            difficulty: 'Hard',
            milestones: [
                { title: 'Setup environment & learn syntax', percent: 10 },
                { title: 'Data structures & algorithms basics', percent: 30 },
                { title: 'Build first small projects', percent: 55 },
                { title: 'Intermediate concepts & frameworks', percent: 80 },
                { title: 'Portfolio project complete', percent: 100 },
            ],
        },
        {
            id: 'university-application',
            title: 'University Application',
            category: 'career',
            emoji: '🏫',
            description: 'Plan and prepare all aspects of university applications',
            estimatedHours: 60,
            defaultWeeklyHours: 8,
            difficulty: 'Medium',
            milestones: [
                { title: 'Research universities & requirements', percent: 15 },
                { title: 'Prepare standardized test scores', percent: 35 },
                { title: 'Write personal statements', percent: 60 },
                { title: 'Gather recommendations & documents', percent: 80 },
                { title: 'Submit applications', percent: 100 },
            ],
        },
        {
            id: 'fitness-student',
            title: 'Build Fitness Habit',
            category: 'health',
            emoji: '🏃',
            description: 'Start a sustainable exercise routine alongside studies',
            estimatedHours: 80,
            defaultWeeklyHours: 5,
            difficulty: 'Easy',
            milestones: [
                { title: 'Start with 3x/week light exercise', percent: 15 },
                { title: 'Establish regular schedule', percent: 35 },
                { title: 'Increase intensity gradually', percent: 60 },
                { title: 'Add variety: cardio + strength', percent: 80 },
                { title: 'Sustainable routine achieved', percent: 100 },
            ],
        },
        {
            id: 'savings-student',
            title: 'Start Saving',
            category: 'finance',
            emoji: '🐷',
            description: 'Build your first emergency fund and learn budgeting',
            estimatedHours: 20,
            defaultWeeklyHours: 1,
            difficulty: 'Easy',
            milestones: [
                { title: 'Track expenses for 1 month', percent: 20 },
                { title: 'Create a simple budget', percent: 40 },
                { title: 'Open savings account', percent: 60 },
                { title: 'Save first $500', percent: 80 },
                { title: 'Emergency fund of 1 month expenses', percent: 100 },
            ],
        },
    ],
    'early-career': [
        {
            id: 'certification',
            title: 'Professional Certification',
            category: 'career',
            emoji: '🏆',
            description: 'Prepare for and earn a professional certification',
            estimatedHours: 150,
            defaultWeeklyHours: 12,
            difficulty: 'Hard',
            milestones: [
                { title: 'Choose certification & register', percent: 5 },
                { title: 'Complete study materials (50%)', percent: 35 },
                { title: 'Complete all study materials', percent: 60 },
                { title: 'Practice exams & review', percent: 85 },
                { title: 'Pass certification exam', percent: 100 },
            ],
        },
        {
            id: 'emergency-fund',
            title: 'Build Emergency Fund',
            category: 'finance',
            emoji: '🏦',
            description: 'Save 3-6 months of living expenses',
            estimatedHours: 24,
            defaultWeeklyHours: 1,
            difficulty: 'Medium',
            milestones: [
                { title: 'Calculate monthly expenses', percent: 10 },
                { title: 'Set up automatic savings', percent: 25 },
                { title: 'Reach 1 month saved', percent: 45 },
                { title: 'Reach 3 months saved', percent: 75 },
                { title: 'Reach 6 months saved', percent: 100 },
            ],
        },
        {
            id: 'muscle-building',
            title: 'Muscle Building Program',
            category: 'health',
            emoji: '🏋️',
            description: 'Progressive overload strength training program',
            estimatedHours: 156,
            defaultWeeklyHours: 6,
            difficulty: 'Hard',
            milestones: [
                { title: 'Learn proper form & nutrition basics', percent: 10 },
                { title: 'Complete beginner program (4 weeks)', percent: 25 },
                { title: 'Progress to intermediate weights', percent: 50 },
                { title: 'Hit strength benchmarks', percent: 75 },
                { title: 'Achieve target physique goals', percent: 100 },
            ],
        },
        {
            id: 'new-language',
            title: 'Learn a New Language',
            category: 'study',
            emoji: '🌍',
            description: 'Reach conversational fluency in a new language',
            estimatedHours: 300,
            defaultWeeklyHours: 7,
            difficulty: 'Hard',
            milestones: [
                { title: 'Learn 500 basic words & phrases', percent: 15 },
                { title: 'Basic grammar & simple conversations', percent: 35 },
                { title: 'Watch media in target language', percent: 55 },
                { title: 'Have extended conversations', percent: 80 },
                { title: 'Pass fluency assessment', percent: 100 },
            ],
        },
        {
            id: 'invest-start',
            title: 'Start Investing',
            category: 'finance',
            emoji: '📈',
            description: 'Learn investing fundamentals and build a portfolio',
            estimatedHours: 40,
            defaultWeeklyHours: 3,
            difficulty: 'Medium',
            milestones: [
                { title: 'Learn investing basics', percent: 20 },
                { title: 'Open brokerage account', percent: 35 },
                { title: 'Make first investment', percent: 55 },
                { title: 'Diversify portfolio', percent: 80 },
                { title: 'Automate regular contributions', percent: 100 },
            ],
        },
    ],
    'mid-career': [
        {
            id: 'leadership',
            title: 'Leadership Development',
            category: 'career',
            emoji: '👔',
            description: 'Develop management and leadership competencies',
            estimatedHours: 100,
            defaultWeeklyHours: 5,
            difficulty: 'Medium',
            milestones: [
                { title: 'Self-assessment & goal setting', percent: 10 },
                { title: 'Complete leadership course', percent: 30 },
                { title: 'Practice with team projects', percent: 55 },
                { title: 'Seek mentorship & feedback', percent: 80 },
                { title: 'Lead a major initiative', percent: 100 },
            ],
        },
        {
            id: 'property-investment',
            title: 'Property Investment',
            category: 'finance',
            emoji: '🏠',
            description: 'Research, plan, and make a property investment',
            estimatedHours: 80,
            defaultWeeklyHours: 4,
            difficulty: 'Hard',
            milestones: [
                { title: 'Research market & financing', percent: 20 },
                { title: 'Get pre-approved for mortgage', percent: 40 },
                { title: 'Property search & evaluation', percent: 60 },
                { title: 'Negotiate & close deal', percent: 85 },
                { title: 'Manage investment', percent: 100 },
            ],
        },
        {
            id: 'marathon',
            title: 'Run a Marathon',
            category: 'health',
            emoji: '🏅',
            description: '16-week marathon training program',
            estimatedHours: 128,
            defaultWeeklyHours: 8,
            difficulty: 'Hard',
            milestones: [
                { title: 'Build base mileage (4 weeks)', percent: 20 },
                { title: 'Increase long runs (4 weeks)', percent: 45 },
                { title: 'Peak mileage (4 weeks)', percent: 70 },
                { title: 'Taper & race prep (3 weeks)', percent: 90 },
                { title: 'Race day!', percent: 100 },
            ],
        },
        {
            id: 'mba-prep',
            title: 'MBA Preparation',
            category: 'study',
            emoji: '📊',
            description: 'Prepare for MBA application and GMAT',
            estimatedHours: 200,
            defaultWeeklyHours: 12,
            difficulty: 'Hard',
            milestones: [
                { title: 'Research programs & requirements', percent: 10 },
                { title: 'GMAT study (quant & verbal)', percent: 40 },
                { title: 'Take GMAT exam', percent: 55 },
                { title: 'Write essays & get recommendations', percent: 80 },
                { title: 'Submit applications', percent: 100 },
            ],
        },
    ],
    'pre-retirement': [
        {
            id: 'retirement-planning',
            title: 'Retirement Fund Optimization',
            category: 'finance',
            emoji: '💎',
            description: 'Optimize retirement savings and plan withdrawal strategy',
            estimatedHours: 40,
            defaultWeeklyHours: 2,
            difficulty: 'Medium',
            milestones: [
                { title: 'Audit current retirement accounts', percent: 15 },
                { title: 'Optimize asset allocation', percent: 35 },
                { title: 'Plan withdrawal strategy', percent: 55 },
                { title: 'Consult financial advisor', percent: 80 },
                { title: 'Finalize retirement plan', percent: 100 },
            ],
        },
        {
            id: 'health-screening',
            title: 'Health Optimization',
            category: 'health',
            emoji: '❤️',
            description: 'Comprehensive health screening and improvement plan',
            estimatedHours: 52,
            defaultWeeklyHours: 4,
            difficulty: 'Easy',
            milestones: [
                { title: 'Complete full health screening', percent: 15 },
                { title: 'Establish exercise routine', percent: 35 },
                { title: 'Optimize nutrition plan', percent: 55 },
                { title: 'Regular monitoring & adjustments', percent: 80 },
                { title: 'Sustainable health habits', percent: 100 },
            ],
        },
        {
            id: 'learn-instrument',
            title: 'Learn Musical Instrument',
            category: 'study',
            emoji: '🎵',
            description: 'Pick up a new instrument and learn to play songs',
            estimatedHours: 200,
            defaultWeeklyHours: 5,
            difficulty: 'Medium',
            milestones: [
                { title: 'Choose instrument & get basics', percent: 10 },
                { title: 'Learn fundamental techniques', percent: 30 },
                { title: 'Play simple songs', percent: 55 },
                { title: 'Learn music theory basics', percent: 75 },
                { title: 'Perform a complete piece', percent: 100 },
            ],
        },
    ],
    'active-senior': [
        {
            id: 'estate-planning',
            title: 'Estate Planning',
            category: 'finance',
            emoji: '📋',
            description: 'Organize estate documents and legacy planning',
            estimatedHours: 30,
            defaultWeeklyHours: 2,
            difficulty: 'Medium',
            milestones: [
                { title: 'Inventory assets & beneficiaries', percent: 20 },
                { title: 'Draft will & power of attorney', percent: 45 },
                { title: 'Set up trusts if needed', percent: 70 },
                { title: 'Review & finalize with attorney', percent: 90 },
                { title: 'Distribute copies to family', percent: 100 },
            ],
        },
        {
            id: 'walking-program',
            title: 'Daily Walking Program',
            category: 'health',
            emoji: '🚶',
            description: 'Build up to 10,000 steps daily with flexibility',
            estimatedHours: 90,
            defaultWeeklyHours: 7,
            difficulty: 'Easy',
            milestones: [
                { title: 'Start with 3,000 steps/day', percent: 15 },
                { title: 'Increase to 5,000 steps/day', percent: 35 },
                { title: 'Add stretching routine', percent: 55 },
                { title: 'Reach 8,000 steps/day', percent: 80 },
                { title: 'Sustain 10,000 steps/day', percent: 100 },
            ],
        },
        {
            id: 'travel-planning',
            title: 'Travel & Adventures',
            category: 'career',
            emoji: '✈️',
            description: 'Plan and organize dream travel experiences',
            estimatedHours: 40,
            defaultWeeklyHours: 3,
            difficulty: 'Easy',
            milestones: [
                { title: 'Create bucket list destinations', percent: 15 },
                { title: 'Research & budget first trip', percent: 35 },
                { title: 'Book & plan first trip', percent: 60 },
                { title: 'Complete first trip', percent: 80 },
                { title: 'Plan next adventure', percent: 100 },
            ],
        },
        {
            id: 'memoir-writing',
            title: 'Write Memoir',
            category: 'study',
            emoji: '📖',
            description: 'Document your life story and wisdom for family',
            estimatedHours: 100,
            defaultWeeklyHours: 5,
            difficulty: 'Medium',
            milestones: [
                { title: 'Outline key life chapters', percent: 15 },
                { title: 'Write first 5 chapters', percent: 40 },
                { title: 'Complete draft', percent: 65 },
                { title: 'Edit & add photos', percent: 85 },
                { title: 'Print & share with family', percent: 100 },
            ],
        },
    ],
};

// Get all goals for a specific life stage
export function getGoalsForStage(stageId) {
    return GOAL_TEMPLATES[stageId] || [];
}

// Get a specific goal template by ID across all stages
export function getGoalTemplateById(goalId) {
    for (const stage of Object.values(GOAL_TEMPLATES)) {
        const found = stage.find(g => g.id === goalId);
        if (found) return found;
    }
    return null;
}
